[project]
name = "pymixtcomp"
version = "0.1.3"
description = "Mixture models with heterogeneous data sets and partially missing data management."
authors = [
  {name = "Vincent Kubicki"},
  {name = "Christophe Biernacki"},
  {name = "Quentin Grimonprez"},
  {name = "Matthieu Marbac-Lourdelle"},
  {name = "Étienne Goffinet"},
  {name = "Serge Iovleff"},
]

readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas (>=2.0.0,<3.0.0)",
    "scikit-learn (>=1.0.0,<2.0.0)",
    "seaborn (>=0.11.0,<0.14.0)",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

keywords=["clustering", "mixture model", "heterogeneous", "missing data"]

[project.urls]
Repository = "https://github.com/modal-inria/MixtComp"

[dependency-groups]
dev = [
    "jupyter (>=1.1.1,<2.0.0)",
]

test = [
    "pytest (>=7.0.0)",
]

[tool.poetry]
include = ["pyMixtComp/pyMixtCompBridge.so"]

packages = [
    {include = "pyMixtComp"}
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"