################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../doc/examples/README.cpp \
../doc/examples/array.cpp \
../doc/examples/at__object_t_key_type.cpp \
../doc/examples/at__object_t_key_type_const.cpp \
../doc/examples/at__size_type.cpp \
../doc/examples/at__size_type_const.cpp \
../doc/examples/at_json_pointer.cpp \
../doc/examples/at_json_pointer_const.cpp \
../doc/examples/back.cpp \
../doc/examples/basic_json__CompatibleArrayType.cpp \
../doc/examples/basic_json__CompatibleIntegerNumberType.cpp \
../doc/examples/basic_json__CompatibleNumberFloatType.cpp \
../doc/examples/basic_json__CompatibleObjectType.cpp \
../doc/examples/basic_json__CompatibleStringType.cpp \
../doc/examples/basic_json__InputIt_InputIt.cpp \
../doc/examples/basic_json__array_t.cpp \
../doc/examples/basic_json__basic_json.cpp \
../doc/examples/basic_json__boolean_t.cpp \
../doc/examples/basic_json__const_int.cpp \
../doc/examples/basic_json__copyassignment.cpp \
../doc/examples/basic_json__istream.cpp \
../doc/examples/basic_json__list_init_t.cpp \
../doc/examples/basic_json__moveconstructor.cpp \
../doc/examples/basic_json__nullptr_t.cpp \
../doc/examples/basic_json__number_float_t.cpp \
../doc/examples/basic_json__number_integer_t.cpp \
../doc/examples/basic_json__object_t.cpp \
../doc/examples/basic_json__size_type_basic_json.cpp \
../doc/examples/basic_json__string_t.cpp \
../doc/examples/basic_json__string_t_value_type.cpp \
../doc/examples/basic_json__value.cpp \
../doc/examples/basic_json__value_ptr.cpp \
../doc/examples/basic_json__value_t.cpp \
../doc/examples/begin.cpp \
../doc/examples/cbegin.cpp \
../doc/examples/cend.cpp \
../doc/examples/clear.cpp \
../doc/examples/count.cpp \
../doc/examples/crbegin.cpp \
../doc/examples/crend.cpp \
../doc/examples/diff.cpp \
../doc/examples/dump.cpp \
../doc/examples/empty.cpp \
../doc/examples/end.cpp \
../doc/examples/erase__IteratorType.cpp \
../doc/examples/erase__IteratorType_IteratorType.cpp \
../doc/examples/erase__key_type.cpp \
../doc/examples/erase__size_type.cpp \
../doc/examples/find__key_type.cpp \
../doc/examples/flatten.cpp \
../doc/examples/front.cpp \
../doc/examples/get__PointerType.cpp \
../doc/examples/get__ValueType_const.cpp \
../doc/examples/get_ptr.cpp \
../doc/examples/get_ref.cpp \
../doc/examples/insert.cpp \
../doc/examples/insert__count.cpp \
../doc/examples/insert__ilist.cpp \
../doc/examples/insert__range.cpp \
../doc/examples/is_array.cpp \
../doc/examples/is_boolean.cpp \
../doc/examples/is_discarded.cpp \
../doc/examples/is_null.cpp \
../doc/examples/is_number.cpp \
../doc/examples/is_number_float.cpp \
../doc/examples/is_number_integer.cpp \
../doc/examples/is_number_unsigned.cpp \
../doc/examples/is_object.cpp \
../doc/examples/is_primitive.cpp \
../doc/examples/is_string.cpp \
../doc/examples/is_structured.cpp \
../doc/examples/json_pointer.cpp \
../doc/examples/json_pointer__to_string.cpp \
../doc/examples/max_size.cpp \
../doc/examples/object.cpp \
../doc/examples/operator__ValueType.cpp \
../doc/examples/operator__equal.cpp \
../doc/examples/operator__equal__nullptr_t.cpp \
../doc/examples/operator__greater.cpp \
../doc/examples/operator__greaterequal.cpp \
../doc/examples/operator__less.cpp \
../doc/examples/operator__lessequal.cpp \
../doc/examples/operator__notequal.cpp \
../doc/examples/operator__notequal__nullptr_t.cpp \
../doc/examples/operator__value_t.cpp \
../doc/examples/operator_deserialize.cpp \
../doc/examples/operator_serialize.cpp \
../doc/examples/operatorarray__key_type.cpp \
../doc/examples/operatorarray__key_type_const.cpp \
../doc/examples/operatorarray__size_type.cpp \
../doc/examples/operatorarray__size_type_const.cpp \
../doc/examples/operatorjson_pointer.cpp \
../doc/examples/operatorjson_pointer_const.cpp \
../doc/examples/parse__array__parser_callback_t.cpp \
../doc/examples/parse__contiguouscontainer__parser_callback_t.cpp \
../doc/examples/parse__istream__parser_callback_t.cpp \
../doc/examples/parse__iteratortype__parser_callback_t.cpp \
../doc/examples/parse__string__parser_callback_t.cpp \
../doc/examples/patch.cpp \
../doc/examples/push_back.cpp \
../doc/examples/push_back__initializer_list.cpp \
../doc/examples/push_back__object_t__value.cpp \
../doc/examples/rbegin.cpp \
../doc/examples/rend.cpp \
../doc/examples/size.cpp \
../doc/examples/swap__array_t.cpp \
../doc/examples/swap__object_t.cpp \
../doc/examples/swap__reference.cpp \
../doc/examples/swap__string_t.cpp \
../doc/examples/type.cpp \
../doc/examples/unflatten.cpp 

OBJS += \
./doc/examples/README.o \
./doc/examples/array.o \
./doc/examples/at__object_t_key_type.o \
./doc/examples/at__object_t_key_type_const.o \
./doc/examples/at__size_type.o \
./doc/examples/at__size_type_const.o \
./doc/examples/at_json_pointer.o \
./doc/examples/at_json_pointer_const.o \
./doc/examples/back.o \
./doc/examples/basic_json__CompatibleArrayType.o \
./doc/examples/basic_json__CompatibleIntegerNumberType.o \
./doc/examples/basic_json__CompatibleNumberFloatType.o \
./doc/examples/basic_json__CompatibleObjectType.o \
./doc/examples/basic_json__CompatibleStringType.o \
./doc/examples/basic_json__InputIt_InputIt.o \
./doc/examples/basic_json__array_t.o \
./doc/examples/basic_json__basic_json.o \
./doc/examples/basic_json__boolean_t.o \
./doc/examples/basic_json__const_int.o \
./doc/examples/basic_json__copyassignment.o \
./doc/examples/basic_json__istream.o \
./doc/examples/basic_json__list_init_t.o \
./doc/examples/basic_json__moveconstructor.o \
./doc/examples/basic_json__nullptr_t.o \
./doc/examples/basic_json__number_float_t.o \
./doc/examples/basic_json__number_integer_t.o \
./doc/examples/basic_json__object_t.o \
./doc/examples/basic_json__size_type_basic_json.o \
./doc/examples/basic_json__string_t.o \
./doc/examples/basic_json__string_t_value_type.o \
./doc/examples/basic_json__value.o \
./doc/examples/basic_json__value_ptr.o \
./doc/examples/basic_json__value_t.o \
./doc/examples/begin.o \
./doc/examples/cbegin.o \
./doc/examples/cend.o \
./doc/examples/clear.o \
./doc/examples/count.o \
./doc/examples/crbegin.o \
./doc/examples/crend.o \
./doc/examples/diff.o \
./doc/examples/dump.o \
./doc/examples/empty.o \
./doc/examples/end.o \
./doc/examples/erase__IteratorType.o \
./doc/examples/erase__IteratorType_IteratorType.o \
./doc/examples/erase__key_type.o \
./doc/examples/erase__size_type.o \
./doc/examples/find__key_type.o \
./doc/examples/flatten.o \
./doc/examples/front.o \
./doc/examples/get__PointerType.o \
./doc/examples/get__ValueType_const.o \
./doc/examples/get_ptr.o \
./doc/examples/get_ref.o \
./doc/examples/insert.o \
./doc/examples/insert__count.o \
./doc/examples/insert__ilist.o \
./doc/examples/insert__range.o \
./doc/examples/is_array.o \
./doc/examples/is_boolean.o \
./doc/examples/is_discarded.o \
./doc/examples/is_null.o \
./doc/examples/is_number.o \
./doc/examples/is_number_float.o \
./doc/examples/is_number_integer.o \
./doc/examples/is_number_unsigned.o \
./doc/examples/is_object.o \
./doc/examples/is_primitive.o \
./doc/examples/is_string.o \
./doc/examples/is_structured.o \
./doc/examples/json_pointer.o \
./doc/examples/json_pointer__to_string.o \
./doc/examples/max_size.o \
./doc/examples/object.o \
./doc/examples/operator__ValueType.o \
./doc/examples/operator__equal.o \
./doc/examples/operator__equal__nullptr_t.o \
./doc/examples/operator__greater.o \
./doc/examples/operator__greaterequal.o \
./doc/examples/operator__less.o \
./doc/examples/operator__lessequal.o \
./doc/examples/operator__notequal.o \
./doc/examples/operator__notequal__nullptr_t.o \
./doc/examples/operator__value_t.o \
./doc/examples/operator_deserialize.o \
./doc/examples/operator_serialize.o \
./doc/examples/operatorarray__key_type.o \
./doc/examples/operatorarray__key_type_const.o \
./doc/examples/operatorarray__size_type.o \
./doc/examples/operatorarray__size_type_const.o \
./doc/examples/operatorjson_pointer.o \
./doc/examples/operatorjson_pointer_const.o \
./doc/examples/parse__array__parser_callback_t.o \
./doc/examples/parse__contiguouscontainer__parser_callback_t.o \
./doc/examples/parse__istream__parser_callback_t.o \
./doc/examples/parse__iteratortype__parser_callback_t.o \
./doc/examples/parse__string__parser_callback_t.o \
./doc/examples/patch.o \
./doc/examples/push_back.o \
./doc/examples/push_back__initializer_list.o \
./doc/examples/push_back__object_t__value.o \
./doc/examples/rbegin.o \
./doc/examples/rend.o \
./doc/examples/size.o \
./doc/examples/swap__array_t.o \
./doc/examples/swap__object_t.o \
./doc/examples/swap__reference.o \
./doc/examples/swap__string_t.o \
./doc/examples/type.o \
./doc/examples/unflatten.o 

CPP_DEPS += \
./doc/examples/README.d \
./doc/examples/array.d \
./doc/examples/at__object_t_key_type.d \
./doc/examples/at__object_t_key_type_const.d \
./doc/examples/at__size_type.d \
./doc/examples/at__size_type_const.d \
./doc/examples/at_json_pointer.d \
./doc/examples/at_json_pointer_const.d \
./doc/examples/back.d \
./doc/examples/basic_json__CompatibleArrayType.d \
./doc/examples/basic_json__CompatibleIntegerNumberType.d \
./doc/examples/basic_json__CompatibleNumberFloatType.d \
./doc/examples/basic_json__CompatibleObjectType.d \
./doc/examples/basic_json__CompatibleStringType.d \
./doc/examples/basic_json__InputIt_InputIt.d \
./doc/examples/basic_json__array_t.d \
./doc/examples/basic_json__basic_json.d \
./doc/examples/basic_json__boolean_t.d \
./doc/examples/basic_json__const_int.d \
./doc/examples/basic_json__copyassignment.d \
./doc/examples/basic_json__istream.d \
./doc/examples/basic_json__list_init_t.d \
./doc/examples/basic_json__moveconstructor.d \
./doc/examples/basic_json__nullptr_t.d \
./doc/examples/basic_json__number_float_t.d \
./doc/examples/basic_json__number_integer_t.d \
./doc/examples/basic_json__object_t.d \
./doc/examples/basic_json__size_type_basic_json.d \
./doc/examples/basic_json__string_t.d \
./doc/examples/basic_json__string_t_value_type.d \
./doc/examples/basic_json__value.d \
./doc/examples/basic_json__value_ptr.d \
./doc/examples/basic_json__value_t.d \
./doc/examples/begin.d \
./doc/examples/cbegin.d \
./doc/examples/cend.d \
./doc/examples/clear.d \
./doc/examples/count.d \
./doc/examples/crbegin.d \
./doc/examples/crend.d \
./doc/examples/diff.d \
./doc/examples/dump.d \
./doc/examples/empty.d \
./doc/examples/end.d \
./doc/examples/erase__IteratorType.d \
./doc/examples/erase__IteratorType_IteratorType.d \
./doc/examples/erase__key_type.d \
./doc/examples/erase__size_type.d \
./doc/examples/find__key_type.d \
./doc/examples/flatten.d \
./doc/examples/front.d \
./doc/examples/get__PointerType.d \
./doc/examples/get__ValueType_const.d \
./doc/examples/get_ptr.d \
./doc/examples/get_ref.d \
./doc/examples/insert.d \
./doc/examples/insert__count.d \
./doc/examples/insert__ilist.d \
./doc/examples/insert__range.d \
./doc/examples/is_array.d \
./doc/examples/is_boolean.d \
./doc/examples/is_discarded.d \
./doc/examples/is_null.d \
./doc/examples/is_number.d \
./doc/examples/is_number_float.d \
./doc/examples/is_number_integer.d \
./doc/examples/is_number_unsigned.d \
./doc/examples/is_object.d \
./doc/examples/is_primitive.d \
./doc/examples/is_string.d \
./doc/examples/is_structured.d \
./doc/examples/json_pointer.d \
./doc/examples/json_pointer__to_string.d \
./doc/examples/max_size.d \
./doc/examples/object.d \
./doc/examples/operator__ValueType.d \
./doc/examples/operator__equal.d \
./doc/examples/operator__equal__nullptr_t.d \
./doc/examples/operator__greater.d \
./doc/examples/operator__greaterequal.d \
./doc/examples/operator__less.d \
./doc/examples/operator__lessequal.d \
./doc/examples/operator__notequal.d \
./doc/examples/operator__notequal__nullptr_t.d \
./doc/examples/operator__value_t.d \
./doc/examples/operator_deserialize.d \
./doc/examples/operator_serialize.d \
./doc/examples/operatorarray__key_type.d \
./doc/examples/operatorarray__key_type_const.d \
./doc/examples/operatorarray__size_type.d \
./doc/examples/operatorarray__size_type_const.d \
./doc/examples/operatorjson_pointer.d \
./doc/examples/operatorjson_pointer_const.d \
./doc/examples/parse__array__parser_callback_t.d \
./doc/examples/parse__contiguouscontainer__parser_callback_t.d \
./doc/examples/parse__istream__parser_callback_t.d \
./doc/examples/parse__iteratortype__parser_callback_t.d \
./doc/examples/parse__string__parser_callback_t.d \
./doc/examples/patch.d \
./doc/examples/push_back.d \
./doc/examples/push_back__initializer_list.d \
./doc/examples/push_back__object_t__value.d \
./doc/examples/rbegin.d \
./doc/examples/rend.d \
./doc/examples/size.d \
./doc/examples/swap__array_t.d \
./doc/examples/swap__object_t.d \
./doc/examples/swap__reference.d \
./doc/examples/swap__string_t.d \
./doc/examples/type.d \
./doc/examples/unflatten.d 


# Each subdirectory must supply rules for building sources it contributes
doc/examples/%.o: ../doc/examples/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


