# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateS4ByRef <- function(listS4) {
    invisible(.Call('RMixtComp_updateS4ByRef', PACKAGE = 'RMixtComp', listS4))
}

updateDFByRef <- function(DF) {
    invisible(.Call('RMixtComp_updateDFByRef', PACKAGE = 'RMixtComp', DF))
}

addColDF <- function(df, name) {
    .Call('RMixtComp_addColDF', PACKAGE = 'RMixtComp', df, name)
}

rcpp_change_var <- function(a) {
    invisible(.Call('RMixtComp_rcpp_change_var', PACKAGE = 'RMixtComp', a))
}

cpp_if <- function(a) {
    .Call('RMixtComp_cpp_if', PACKAGE = 'RMixtComp', a)
}

cpp_if_2 <- function(a) {
    invisible(.Call('RMixtComp_cpp_if_2', PACKAGE = 'RMixtComp', a))
}

cpp_if_3 <- function(a) {
    invisible(.Call('RMixtComp_cpp_if_3', PACKAGE = 'RMixtComp', a))
}

cpp_if_4 <- function(a) {
    .Call('RMixtComp_cpp_if_4', PACKAGE = 'RMixtComp', a)
}

