# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixtCompCluster <- function(dataList, mcStrategy, nbClass, confidenceLevel) {
    .Call('_RMixtComp_mixtCompCluster', PACKAGE = 'RMixtComp', dataList, mcStrategy, nbClass, confidenceLevel)
}

mixtCompPredict <- function(dataList, paramList, mcStrategy, nbClass, confidenceLevel) {
    .Call('_RMixtComp_mixtCompPredict', PACKAGE = 'RMixtComp', dataList, paramList, mcStrategy, nbClass, confidenceLevel)
}

