// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// updateS4ByRef
void updateS4ByRef(Rcpp::List listS4);
RcppExport SEXP RMixtComp_updateS4ByRef(SEXP listS4SEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::List >::type listS4(listS4SEXP );
        updateS4ByRef(listS4);
    }
    return R_NilValue;
END_RCPP
}
// updateDFByRef
void updateDFByRef(Rcpp::DataFrame DF);
RcppExport SEXP RMixtComp_updateDFByRef(SEXP DFSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DF(DFSEXP );
        updateDFByRef(DF);
    }
    return R_NilValue;
END_RCPP
}
// addColDF
Rcpp::List addColDF(Rcpp::DataFrame df, std::string name);
RcppExport SEXP RMixtComp_addColDF(SEXP dfSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP );
        Rcpp::traits::input_parameter< std::string >::type name(nameSEXP );
        Rcpp::List __result = addColDF(df, name);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_change_var
void rcpp_change_var(Rcpp::NumericVector a);
RcppExport SEXP RMixtComp_rcpp_change_var(SEXP aSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP );
        rcpp_change_var(a);
    }
    return R_NilValue;
END_RCPP
}
// cpp_if
Rcpp::NumericVector cpp_if(Rcpp::NumericVector a);
RcppExport SEXP RMixtComp_cpp_if(SEXP aSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP );
        Rcpp::NumericVector __result = cpp_if(a);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cpp_if_2
void cpp_if_2(Rcpp::NumericVector a);
RcppExport SEXP RMixtComp_cpp_if_2(SEXP aSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP );
        cpp_if_2(a);
    }
    return R_NilValue;
END_RCPP
}
// cpp_if_3
void cpp_if_3(Rcpp::NumericVector a);
RcppExport SEXP RMixtComp_cpp_if_3(SEXP aSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP );
        cpp_if_3(a);
    }
    return R_NilValue;
END_RCPP
}
// cpp_if_4
Rcpp::NumericVector cpp_if_4(Rcpp::NumericVector a);
RcppExport SEXP RMixtComp_cpp_if_4(SEXP aSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP );
        Rcpp::NumericVector __result = cpp_if_4(a);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
