name: MixtComp C++ Library
on:
  push:
    branches:
      - master
      - staging
    paths:
      - MixtComp/**
      - .github/workflows/MixtComp.yml
  pull_request:
    branches:
      - master
      - staging
    paths:
      - MixtComp/**
      - .github/workflows/MixtComp.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MixtComp
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install MixtComp dependencies
        run: sudo apt-get install cmake libboost-all-dev libeigen3-dev libxml2-dev lcov valgrind
      - name: Compile MixtComp
        working-directory: MixtComp
        run: ./build.sh Debug
      - name: Test MixtComp
        working-directory: MixtComp
        run: ./utest.sh
      - name: Run valgrind
        working-directory: MixtComp
        run: ./valgrindRun.sh
