name: pyMixtComp
on:
  push:
    branches:
      - master
      - staging
    paths:
      - MixtComp/**
      - pyMixtComp/**
      - .github/workflows/pyMixtComp.yml
  pull_request:
    branches:
      - master
      - staging
    paths:
      - MixtComp/**
      - pyMixtComp/**
      - .github/workflows/pyMixtComp.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MixtComp
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install MixtComp dependencies
        run: sudo apt-get install cmake libboost-all-dev libeigen3-dev libxml2-dev lcov
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Tests dependencies
        run: pip install pytest flake8
      - name: Install Other Python Dependencies
        working-directory: pyMixtComp/python
        run: pip install -r requirements.txt
      - name: Compile PyMixtCompBridge
        working-directory: pyMixtComp
        run: ./build.sh
      - name: Test PyMixtCompBridge
        working-directory: pyMixtComp
        run: ./utest.sh
      - name: Copy PyMixtCompBridge.so
        working-directory: pyMixtComp/python
        run: cp ../build/lib/pyMixtCompBridge.so pyMixtComp/pyMixtCompBridge.so
      - name: Lint with flake8
        working-directory: pyMixtComp/python
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        working-directory: pyMixtComp/python
        run: pytest tests
