name: Test RMixtComp

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging


jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Install RMixtCompIO dependencies
        working-directory: RMixtCompIO
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Copy MixtComp files
        working-directory: RMixtCompIO
        run: |
          make clean
          make updateLib

      - name: Compile Rcpp Attributes for RMixtCompIO
        working-directory: RMixtCompIO
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: Rcpp::compileAttributes()
        shell: Rscript {0}

      - name: Check RMixtCompIO
        working-directory: RMixtCompIO
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        working-directory: RMixtCompIO
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: RMixtCompIO/check

      - name: Install local RMixtCompIO
        working-directory: RMixtCompIO
        run: R CMD INSTALL --no-multiarch --with-keep.source .

      - name: Install RMixtCompUtilities dependencies
        working-directory: RMixtCompUtilities
        run: remotes::update_packages(setdiff(remotes::local_package_deps(pkgdir = ".", dependencies = TRUE), "RMixtCompIO"))
        shell: Rscript {0}

      - name: Check RMixtCompUtilities
        working-directory: RMixtCompUtilities
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        working-directory: RMixtCompUtilities
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: RMixtCompUtilities/check